HULY_VERSION=v0.7.426
DESKTOP_CHANNEL=0.7.426
DOCKER_NAME=Huly

HULY_GIT_REPOSITORY=https://github.com/mizhtech/huly-platform.git
HULY_GIT_BRANCH=dev-v0.7.426
HULY_SOURCE_DIR=./source/huly-platform

HOST_ADDRESS=your-domain.com
SECURE=true
HTTP_PORT=8087
HTTP_BIND=127.0.0.1
SSL_CERTIFICATE=/apps/certs/your-domain.com/fullchain.pem
SSL_CERTIFICATE_KEY=/apps/certs/your-domain.com/privkey.pem

TITLE=Huly
DEFAULT_LANGUAGE=vi
LAST_NAME_FIRST=true
PLATFORM_ADMIN_EMAILS=admin

CR_DATABASE=defaultdb
CR_USERNAME=selfhost
CR_USER_PASSWORD=change-me

REDPANDA_ADMIN_USER=superadmin
REDPANDA_ADMIN_PWD=change-me

EXTERNAL_MINIO_NETWORK=your-external-network
EXTERNAL_MINIO_ENDPOINT=minio.internal:9000
EXTERNAL_MINIO_URL=http://minio.internal:9000
EXTERNAL_MINIO_ACCESS_KEY=change-me
EXTERNAL_MINIO_SECRET_KEY=change-me
EXTERNAL_MINIO_REGION=local
BACKUP_BUCKET_NAME=huly-backups

VOLUME_CR_DATA_PATH=
VOLUME_CR_CERTS_PATH=
VOLUME_REDPANDA_PATH=

SECRET=change-me
