#!/bin/bash
set -euo pipefail

CONFIG_FILE="${CONFIG_FILE:-huly_v7.conf}"
if [ -f "$CONFIG_FILE" ]; then
    # shellcheck disable=SC1090
    source "$CONFIG_FILE"
fi

: "${HOST_ADDRESS:?HOST_ADDRESS is required}"
: "${HTTP_PORT:?HTTP_PORT is required}"

RECREATE=false
if [[ "${1:-}" == "--recreate" ]]; then
    RECREATE=true
fi

if [[ "$RECREATE" == true ]]; then
    cp .template.nginx.conf nginx.conf
    echo "nginx.conf has been recreated from the template."
elif [ ! -f "nginx.conf" ]; then
    echo "nginx.conf not found, creating from template."
    cp .template.nginx.conf nginx.conf
else
    echo "nginx.conf already exists. Updating managed Huly directives."
    echo "Run with --recreate to fully overwrite nginx.conf."
fi

sed -i.bak "s|server_name .*;|server_name ${HOST_ADDRESS};|" ./nginx.conf
sed -i.bak "s|proxy_pass .*;|proxy_pass http://${HTTP_BIND:-127.0.0.1}:${HTTP_PORT};|" ./nginx.conf

# Remove directives generated by an earlier run before adding the current TLS state.
sed -i.bak '/^[[:space:]]*ssl_certificate[[:space:]]/d' ./nginx.conf
sed -i.bak '/^[[:space:]]*ssl_certificate_key[[:space:]]/d' ./nginx.conf

# Remove the managed HTTP redirect block, if present.
if grep -q '# ! DO NOT REMOVE COMMENT' nginx.conf; then
    sed -i.bak '/# ! DO NOT REMOVE COMMENT/,/# DO NOT REMOVE COMMENT !/d' nginx.conf
fi

if [[ -n "${SECURE:-}" ]]; then
    : "${SSL_CERTIFICATE:?SSL_CERTIFICATE is required when SECURE is enabled}"
    : "${SSL_CERTIFICATE_KEY:?SSL_CERTIFICATE_KEY is required when SECURE is enabled}"

    if [[ ! -f "$SSL_CERTIFICATE" ]]; then
        echo "SSL certificate not found: $SSL_CERTIFICATE" >&2
        exit 1
    fi
    if [[ ! -f "$SSL_CERTIFICATE_KEY" ]]; then
        echo "SSL certificate key not found: $SSL_CERTIFICATE_KEY" >&2
        exit 1
    fi

    sed -i.bak -E 's|^[[:space:]]*listen .*;|    listen 443 ssl;|' ./nginx.conf
    sed -i.bak "/^[[:space:]]*listen 443 ssl;/a\\
    ssl_certificate ${SSL_CERTIFICATE};\\
    ssl_certificate_key ${SSL_CERTIFICATE_KEY};" ./nginx.conf

    cat >> ./nginx.conf <<EOF

# ! DO NOT REMOVE COMMENT
# DO NOT MODIFY, CHANGES WILL BE OVERWRITTEN
server {
    listen 80;
    server_name ${HOST_ADDRESS};
    return 301 https://\$host\$request_uri;
}
# DO NOT REMOVE COMMENT !
EOF
else
    sed -i.bak -E 's|^[[:space:]]*listen .*;|    listen 80;|' ./nginx.conf
fi

rm -f ./nginx.conf.bak

echo "Generated nginx.conf for ${HOST_ADDRESS}."
if [[ -n "${SECURE:-}" ]]; then
    echo "TLS certificate: $SSL_CERTIFICATE"
    echo "TLS private key: $SSL_CERTIFICATE_KEY"
fi

read -p "Do you want to validate and reload Nginx now? (Y/n): " RUN_NGINX
case "${RUN_NGINX:-Y}" in
    [Yy]* )
        echo -e "\033[1;32mRunning 'nginx -t'...\033[0m"
        sudo nginx -t
        echo -e "\033[1;32mReloading Nginx...\033[0m"
        sudo nginx -s reload
        ;;
    [Nn]* )
        echo "Validate with 'sudo nginx -t' before reloading Nginx."
        ;;
esac
